### ISSUE TITLE
DS03 Light Not Working (Fan Works)

### ISSUE THREAD

**Issue by CaseyTal** [paullj1/TreatLife-HomeKit#6]
I had my Light/Fan combo in the Tuya app, but wanted it in Homekit and no longer in the cloud.

After soldering and flashing the DS03.bin file to my TreatLife Fan/Light Combo, my light functionality is not working. I got the device added to my Wifi and the Home app. I can control the fan through homekit and the switch and it works. The light turns white like it should be on for the light, but no light. I can turn it on and off through the switch and the Home app, but they don't actually turn the light itself on and off.

Did I burn something up while I was soldering? Is there anything I can check?

When I removed power to disable the switch, I only removed the black wire and took the top off. I reinstalled the top and rewired the black wire, so nothing else has changed other than the board itself.

**Comment by CaseyTal** [comment]
I will also note that I followed the commands from another tutorial and flashed directly from Tuya to this build using this command on Raspberry Pi Zero W:
esptool.py --port /dev/ttyS0 write_flash -fm dout 0x0 DS03.bin

**Comment by CaseyTal** [comment]
Huh. I ended up removing the device and connecting it back up and now it works. Swear I’ve done that a million times, but I’m not going to complain.

**Comment by paullj1** [comment]
Haha no worries, glad it’s working for you!
