### ISSUE TITLE
Unable to re-add device to homekit after resetting and removing in Home App

### ISSUE THREAD

**Issue by CaseyTal** [paullj1/TreatLife-HomeKit#7]
Is there a way to wipe the switch completely including any saved Home app connections? I am no longer able to find the switch in the Home app to add it.

I have 2 switches, but only have one of them connected so far. They're both connected to the same WiFi network. I'm just unable to add the second switch at all.

**Comment by paullj1** [comment]
Sorry, the only way to reset the HomeKit ID, is to “upgrade” the firmware.
Get it into setup mode (hold the main button for 8 seconds), then browse to
the web interface, and upload a “new” firmware (it can be the old version).
That should reset it completely.

**Comment by CaseyTal** [comment]
Can two devices of the same make and model cause this issue? I can only get one connected. 

Is there a chance I need to reflash?

I’ve power cycled the breaker a few times and each time it reconnects to the WiFi properly, but the Home app just never sees it.

**Comment by paullj1** [comment]
That shouldn’t be the problem, I have four DS03s on the same network.  They
each get unique IDs.  If you added the device to HomeKit, and then removed
it while the device is offline, there’s a chance that HomeKit won’t
recognize it, and the device needs a new unique ID. Unfortunately, the only
way you can make it get one is to re-flash (which you can do without
opening it back up, you’ll just need to use the WiFi manager interface to
do it).

**Comment by CaseyTal** [comment]
Okay. No worries on that. How do i reflash using WiFi manager?

**Comment by CaseyTal** [comment]
Deleting my last post because I just now realized how stupid it was. You clearly stated I could use WiFi manager interface to do it. What is the URL I would navigate to? I tried downgrade to 1.9.0 then upgraded back to 1.9.1. I'm assuming a reflash would be different from updating/downgrading.

**Comment by CaseyTal** [comment]
Well, I think I might’ve really broke it. I tried downgrading from 1.9.1 to 1.7.0. I can still ping it but cannot get the AP to work or access it via it’s ip on the router. But I can still ping it. 

Any suggestions? Sorry to be a PITA.

**Comment by CaseyTal** [comment]
Is there any way to SSH or Arduino IDE over IP so I don’t have to disassemble it again?

**Comment by paullj1** [comment]
Hey! Yeah, I did mean the WiFi manager, and I was suggesting flashing with
the same version.  Unfortunately, you might need to open it back up again
if it’s completely unresponsive.  Before you do that, I’d flip the breaker,
and try getting it into setup mode. I don’t think anything in 1.7 would
break it necessarily, but it’s also been a while.  The good news is, those
chips are pretty resilient.  I’ve had a them survive several bad flashes.

**Comment by CaseyTal** [comment]
I ended up disassembling the switch again and flashed it again and was able to add it immediately. Have all 3 switches online in HomeKit and working. 

I have been trying to figure out the best way to set these up without Homebridge or something like it for a couple years now. This is so awesome and I can’t thank you enough!!

Do you have a donation link? I’d love to thank you for your time and efforts.

**Comment by paullj1** [comment]
That’s great to hear!! Glad you got it working, and no sweat at all!  It’s really just nice knowing that other people are benefiting, but if you feel so inclined, here’s a PayPal donate link:

https://www.paypal.com/donate/?hosted_button_id=R7PT2GQH8D99Q

**Comment by CaseyTal** [comment]
Thanks again. I donated some for a few coffees and/or beers. You are awesome!!

**Comment by paullj1** [comment]
Got it, thanks!  Really appreciate it!
